Pod::Spec.new do |s|
  s.name         = 'QanivaUnityFramework'
  s.version      = '0.1.0'
  s.summary      = 'Vendored UnityFramework produced by the Unity iOS export'
  s.description  = <<-DESC
    Wrapper pod that vendors + embeds UnityFramework.framework generated by
    scripts/export-unity-ios.sh into ios/UnityFramework.framework. Only added to
    the Podfile when that export exists. The framework binary is a build artifact
    and is git-ignored; regenerate it, never commit it.
  DESC
  s.homepage     = 'https://github.com/ranuelyn/qaniva'
  s.license      = { :type => 'Proprietary' }
  s.author       = 'Qaniva'
  s.platforms    = { :ios => '15.1' }
  s.source       = { :path => '.' }
  s.vendored_frameworks = 'ios/UnityFramework.framework'
end
