import { z } from 'zod';
import { PROTOCOL_VERSION, SIMULATION_FAILURE_CODES, SIMULATION_MODES } from './protocol';
import { attemptSummarySchema } from './attempt-summary';

/**
 * Every bridge message shares this envelope. Payload shape is discriminated by `type`.
 */
const envelopeBase = {
  protocolVersion: z.literal(PROTOCOL_VERSION),
  /** UUID v4 generated by the sender; used for logging/correlation, not ordering. */
  messageId: z.string().uuid(),
  /** ISO-8601 timestamp from the sender's clock. */
  sentAt: z.string().datetime(),
};

export const difficultySchema = z.enum(['standard', 'hard']);
export type Difficulty = z.infer<typeof difficultySchema>;

// --- RN -> Unity -----------------------------------------------------------

export const startSimulationMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('START_SIMULATION'),
  payload: z.object({
    caseId: z.string().min(1),
    caseVersion: z.number().int().positive(),
    attemptId: z.string().uuid(),
    locale: z.string().min(2),
    difficulty: difficultySchema,
    /** Deterministic RNG seed. Same seed + same actions => same outcome. */
    seed: z.number().int().nonnegative(),
    /** Runtime mode; production launches always send "interactive". */
    mode: z.enum(SIMULATION_MODES).default('interactive'),
  }),
});

export const pauseSimulationMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('PAUSE_SIMULATION'),
  payload: z.object({}).strict(),
});

export const resumeSimulationMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('RESUME_SIMULATION'),
  payload: z.object({}).strict(),
});

export const exitSimulationMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('EXIT_SIMULATION'),
  payload: z.object({
    reason: z.enum(['user_quit', 'app_background', 'host_navigation']),
  }),
});

export const rnToUnityMessageSchema = z.discriminatedUnion('type', [
  startSimulationMessageSchema,
  pauseSimulationMessageSchema,
  resumeSimulationMessageSchema,
  exitSimulationMessageSchema,
]);
export type RnToUnityMessage = z.infer<typeof rnToUnityMessageSchema>;

// --- Unity -> RN ---------------------------------------------------------

export const simulationReadyMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('SIMULATION_READY'),
  payload: z.object({
    caseId: z.string().min(1),
    attemptId: z.string().uuid(),
    /** Seconds Unity took from START_SIMULATION to first rendered frame. */
    warmupSec: z.number().nonnegative(),
  }),
});

export const simulationCompletedMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('SIMULATION_COMPLETED'),
  payload: z.object({
    attemptId: z.string().uuid(),
    summary: attemptSummarySchema,
  }),
});

export const simulationFailedMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('SIMULATION_FAILED'),
  payload: z.object({
    attemptId: z.string().uuid().optional(),
    code: z.enum(SIMULATION_FAILURE_CODES),
    message: z.string().min(1),
  }),
});

export const exitRequestedMessageSchema = z.object({
  ...envelopeBase,
  type: z.literal('EXIT_REQUESTED'),
  payload: z.object({
    attemptId: z.string().uuid().optional(),
    reason: z.enum(['user_quit', 'unrecoverable_error']),
  }),
});

export const unityToRnMessageSchema = z.discriminatedUnion('type', [
  simulationReadyMessageSchema,
  simulationCompletedMessageSchema,
  simulationFailedMessageSchema,
  exitRequestedMessageSchema,
]);
export type UnityToRnMessage = z.infer<typeof unityToRnMessageSchema>;

export type BridgeMessage = RnToUnityMessage | UnityToRnMessage;

// --- Codec helpers -----------------------------------------------------

export class BridgeDecodeError extends Error {
  constructor(
    message: string,
    readonly issues?: unknown,
  ) {
    super(message);
    this.name = 'BridgeDecodeError';
  }
}

/** Serialize a message for transport across the native bridge. */
export function encodeMessage(message: BridgeMessage): string {
  return JSON.stringify(message);
}

function parseJson(raw: string): unknown {
  try {
    return JSON.parse(raw) as unknown;
  } catch (err) {
    throw new BridgeDecodeError('Bridge payload is not valid JSON', err);
  }
}

/** Parse + validate a message coming FROM React Native (Unity side uses the C# mirror). */
export function decodeRnToUnity(raw: string): RnToUnityMessage {
  const result = rnToUnityMessageSchema.safeParse(parseJson(raw));
  if (!result.success) {
    throw new BridgeDecodeError('Invalid RN->Unity message', result.error.issues);
  }
  return result.data;
}

/** Parse + validate a message coming FROM Unity into React Native. */
export function decodeUnityToRn(raw: string): UnityToRnMessage {
  const result = unityToRnMessageSchema.safeParse(parseJson(raw));
  if (!result.success) {
    throw new BridgeDecodeError('Invalid Unity->RN message', result.error.issues);
  }
  return result.data;
}
